{-# OPTIONS -w -O0 #-}
{- |
Module      :  EVT/ATC_EVT.der.hs
Description :  generated ShATermConvertible instances
Copyright   :  (c) DFKI GmbH 2012
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(derive Typeable instances)

Automatic derivation of instances via DrIFT-rule ShATermConvertible
  for the type(s):
'EVT.AS.MACHINE'
'EVT.AS.EVTBasicExt'
'EVT.AS.EVENT'
'EVT.AS.GUARD'
'EVT.AS.ACTION'
'EVT.AS.EVTQualId'
'EVT.AS.EVTSymbol'
'EVT.AS.EVTSYMB_MAP_ITEMS'
'EVT.AS.EVTSYMB_OR_MAP'
'EVT.AS.EVTSYMB_ITEMS'
'EVT.AS.EVTRawSymbol'
'EVT.SignEVT.EVTSignature'
'EVT.SignEVT.EVTCASLSen'
'EVT.SignEVT.EVTMorphism'
-}

{-
Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
EVT/AS.hs
EVT/SignEVT.hs
-}

module EVT.ATC_EVT () where

import ATC.GlobalAnnotations
import ATerm.Lib
import CASL.AS_Basic_CASL
import CASL.ATC_CASL ()
import CASL.Morphism as CASL_Morphism
import CASL.Overload
import CASL.Sign
import Common.AS_Annotation
import Common.Doc
import Common.DocUtils
import Common.GlobalAnnotations
import Common.Id as Id
import Common.Result
import Common.Token
import Data.Data
import Data.Set as Set
import EVT.AS
import EVT.Keywords
import EVT.SignEVT
import qualified CASL.MapSentence as CASL_MapSen
import qualified Data.Map as Map

{-! for EVT.AS.MACHINE derive : ShATermConvertible !-}
{-! for EVT.AS.EVTBasicExt derive : ShATermConvertible !-}
{-! for EVT.AS.EVENT derive : ShATermConvertible !-}
{-! for EVT.AS.GUARD derive : ShATermConvertible !-}
{-! for EVT.AS.ACTION derive : ShATermConvertible !-}
{-! for EVT.AS.EVTQualId derive : ShATermConvertible !-}
{-! for EVT.AS.EVTSymbol derive : ShATermConvertible !-}
{-! for EVT.AS.EVTSYMB_MAP_ITEMS derive : ShATermConvertible !-}
{-! for EVT.AS.EVTSYMB_OR_MAP derive : ShATermConvertible !-}
{-! for EVT.AS.EVTSYMB_ITEMS derive : ShATermConvertible !-}
{-! for EVT.AS.EVTRawSymbol derive : ShATermConvertible !-}
{-! for EVT.SignEVT.EVTSignature derive : ShATermConvertible !-}
{-! for EVT.SignEVT.EVTCASLSen derive : ShATermConvertible !-}
{-! for EVT.SignEVT.EVTMorphism derive : ShATermConvertible !-}
